"""initial schema

Revision ID: 72ea2afdd1ab
Revises: d4c96947d3c4
Create Date: 2026-08-23 11:38:21.147845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ea2afdd1ab'
down_revision: Union[str, Sequence[str], None] = 'd4c96947d3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_profile_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_profile_id'], ['vendor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_vendor_profile_id'), 'reviews', ['vendor_profile_id'], unique=False)
    op.add_column('vendor_profiles', sa.Column('what_he_sells', sa.String(length=255), nullable=True))
    op.add_column('vendor_profiles', sa.Column('regularity', sa.String(length=20), nullable=True))
    op.add_column('vendor_profiles', sa.Column('is_movable', sa.Boolean(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('typical_latitude', sa.Float(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('typical_longitude', sa.Float(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('approx_sales_per_day', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('vendor_profiles', 'business_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_profiles', 'business_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('vendor_profiles', 'approx_sales_per_day')
    op.drop_column('vendor_profiles', 'typical_longitude')
    op.drop_column('vendor_profiles', 'typical_latitude')
    op.drop_column('vendor_profiles', 'is_movable')
    op.drop_column('vendor_profiles', 'regularity')
    op.drop_column('vendor_profiles', 'what_he_sells')
    op.drop_index(op.f('ix_reviews_vendor_profile_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
